In [1]:
"""
Test of manually building a low-rank density matrix that reproduces energy of (H_2)_2
"""

from pyscf import gto, scf
import numpy as np

# Build two H3 molecules far apart (say 10 Angstroms separation)
mol = gto.Mole()
mol.atom = '''
H 0 0 0
H 0.74 0 0.
H 9 0 0
H 9.74 0 0
'''
mol.basis = 'sto-3g'
mol.unit = 'Angstrom'
mol.build()

# RHF calculation
mf = scf.RHF(mol)
mf.kernel()
D = mf.make_rdm1()
h = mf.get_hcore()
eri = mol.intor('int2e')
J = np.einsum('rs,pqrs->pq', D, eri)
K = np.einsum('rs,prqs->pq', D, eri)

F = h + 0.5*(2 * J - K)
d, U = np.linalg.eigh(D)
E1 = 0.5 * np.trace(D@(h + F)) + mol.energy_nuc()
C = mf.mo_coeff

print(np.trace(D))
print(d)
print('|DF - FD|: ', np.trace(D@F - F@D))
print(mf.e_tot)

nocc = mf.mo_occ
print(C)
print(nocc)

i = 3
# D2 = U[:,i:i+1] @ np.diag(d[i:i+1]) @ U[:,i:i+1].T*2
davg = 0.5 * (d[2:3]+d[3:4])
D2 = U[:,i:i+1] @ np.diag(davg) @ U[:,i:i+1].T*2
D3 = (U[:,2:3]+U[:,3:4]) @ np.diag(davg) @ (U[:,2:3] + U[:,3:4]).T
print(U)
print('U[2:3]++ = ', (U[:,2:3]+U[:,3:4]).T)
print('d_avg = ', davg)
# D2 = U[:,2:4] @ np.diag(d[2:4]) @ U[:,2:4].T
# D2 = U[i:i+1, :].T @ np.diag(d[i:i+1]) @ U[i:i+1, :]*2
E2 = 0.5 * np.trace(D2@(h + F)) + mol.energy_nuc()
E3 = 0.5 * np.trace(D3@(h + F)) + mol.energy_nuc()
print('E1 = ', E1)
print('E2 = ', E2)
print('E3 = ', E3)
# 'Bosianise': Plug everything into lowest eigenvector
print("|E2 - E1| = ", np.linalg.norm(E2 - E1))
# Average between eigen-vectors & -values
print("|E3 - E1| = ", np.linalg.norm(E3 - E1))

# Confirm matching with PySCF Fock matrix
assert np.allclose(F, mf.get_fock()), "Mismatch in Fock matrix!"


converged SCF energy = -2.23351819973673
2.409822744204587
[-1.09004037e-17  7.84216674e-17  1.20491137e+00  1.20491137e+00]
|DF - FD|:  -1.1102230246251565e-16
-2.2335181997367304
[[ 0.38808204  0.38808221  0.857337   -0.85733616]
 [ 0.38809798  0.38809815 -0.85732978  0.85732895]
 [ 0.38809815 -0.38809798 -0.85732895 -0.85732978]
 [ 0.38808221 -0.38808204  0.85733616  0.857337  ]]
[2. 2. 0. 0.]
[[-0.66259786 -0.24695064  0.49998909 -0.49999037]
 [ 0.66257064  0.2469405   0.50000963 -0.50001091]
 [-0.2469405   0.66257064  0.50001091  0.50000963]
 [ 0.24695064 -0.66259786  0.49999037  0.49998909]]
U[2:3]++ =  [[-1.27337266e-06 -1.27222747e-06  1.00002054e+00  9.99979461e-01]]
d_avg =  [1.20491137]
E1 =  -2.2335181997367304
E2 =  -2.2335181986919697
E3 =  -2.233518199736726
|E2 - E1| =  1.0447607223795785e-09
|E3 - E1| =  4.440892098500626e-15


In [2]:
"""
Find low-rank representation of D by minimizing tr((D-D_lr)*F) (i.e. that reproduces energy)

Parameters:
R: distance of H2s: H2 -----(R)----- H2
r: rank of rdm
"""

from pyscf import gto, scf
import numpy as np
import torch
from scipy.linalg import polar


def prepare_H4(R):
    mol = gto.Mole()
    mol.atom = f"""
    H 0 0 0
    H 0.74 0 0.
    H {R} 0 0
    H {R}.74 0 0
    """
    mol.basis = 'sto-3g'
    mol.unit = 'Angstrom'
    mol.build()

    # RHF calculation
    mf = scf.RHF(mol)
    mf.kernel()
    D = torch.tensor(mf.make_rdm1(), dtype=torch.float64)
    h = mf.get_hcore()
    eri = mol.intor('int2e')
    J = np.einsum('rs,pqrs->pq', D, eri)
    K = np.einsum('rs,prqs->pq', D, eri)
    enuc = mol.energy_nuc()

    F = h + 0.5*(2 * J - K)
    # print(f"Correct HF energy: {mf.e_tot}")
    return torch.tensor(h + F, dtype=torch.float64), D, mf, enuc, mol

def energy(D, F, enuc):
    return 0.5 * torch.trace(D@F) + enuc

def random_unitary(m, r):
    A = torch.randn(m, r, dtype=torch.float64)
    Q, _ = torch.linalg.qr(A)
    return Q

def buildD(U, d):
    return U @ torch.diag(d) @ U.T

def loss(U, d, D, F):
    D2 = buildD(U, d)
    return torch.norm(torch.trace((D - D2) @ F))

def polar_decomp (m, r):   # express polar decomposition in terms of singular-value decomposition
    U, S, Vh = torch.linalg.svd(m, full_matrices=False)
    u = U @ Vh
    # p = Vh.T.conj() @ S.diag().to (dtype = m.dtype) @ Vh
    return  u, None

def output(i, L0, L1, U, d, r, D, F):
    Dnew = buildD(U, d)
    e = energy(Dnew, F, enuc).item()
    err = torch.trace(Dnew @ F - F @ Dnew)
    print(i, L0.item(), L1.item(), err.item(), e - mf.e_tot)

def riemannian_steepest_descent(D, F, loss, r, h = 1e-4, iterations = 201, *args):
    U = random_unitary(F.shape[0], r)
    d = torch.abs(torch.randn(r, dtype=torch.float64, requires_grad=True))
    d *= nocc / torch.sum(d)
    # d /= torch.sum(d)
    for i in range(iterations):
        # gradients
        Utmp = U.detach().clone().requires_grad_()
        dtmp = d.detach().clone().requires_grad_()
        L0 = loss(Utmp, dtmp, D, F, *args)
        L0.backward(retain_graph=True)
        dU = Utmp.grad.detach()
        dd = dtmp.grad.detach()

        # step
        U_bk = U.clone()
        U = U - h * dU
        d = d - h * dd
        # d = d / torch.sum(d) * nocc

        U, _ = polar_decomp(U, r)

        L1 = loss(U, d, D, F, *args)

        err = torch.norm(L1 - L0)
        print(i, L0.item(), L1.item(), err.item())
        # output(i, L0, L1, U, d, r, D, F)

        if L1 < L0:
            h *= 1.5
        else:
            h /= 2.
            U = U_bk
            if h < 1e-14 or err < 1e-12:
                break
    return U, d

# Build two H3 molecules far apart (say 10 Angstroms separation)
R = 8
r = 4
F, D, mf, enuc, mol = prepare_H4(R)
nocc = torch.sum(torch.tensor(mf.mo_occ))
U, d = riemannian_steepest_descent(D, F, loss, r, 1e-4, 200)
print(U, d)

Dnew = U @ torch.diag(d) @ U.T
print(Dnew)
print(energy(Dnew, F, enuc))
def hf_energy(U, d, hcore, eri, mol, rdm, S):
    D = buildD(U, d)
    # replace with low-rank version for D if available
    J = torch.einsum('rs,pqrs->pq', rdm, eri)
    K = torch.einsum('rs,prqs->pq', rdm, eri)
    enuc = mol.energy_nuc()
    F = 2*hcore + 0.5*(2 * J - K)
    return 0.5 * torch.trace(D@F) + enuc


hcore = torch.tensor(mf.get_hcore())
eri = torch.tensor(mol.intor('int2e'))
S = torch.tensor(mf.get_ovlp())
Dnew = buildD(U, d)
print('E_HF(U, d, Dnew) = ', hf_energy(U, d, hcore, eri, mol, Dnew, S))
print('energy(Dnew) = ', energy(Dnew, F, enuc))

print('E_HF(U, d, D) = ', hf_energy(U, d, hcore, eri, mol, D, S))
print('energy(D) = ', energy(D, F, enuc))
"""
@TODO: Maybe this doesn't work because I'm only relaxing tr((D-Dnew)F) but F depends on D as well
it should be tr(Dnew F(Dnew)) = tr(D @ F(D))
"""

converged SCF energy = -2.23351786522334
0 1.1760780510084288 1.1740406440396112 0.002037406968817601
1 1.1740406440396112 1.1709840740598347 0.0030565699797764356
2 1.1709840740598347 1.1663981834316242 0.004585890628210576
3 1.1663981834316242 1.1595170114356148 0.00688117199600935
4 1.1595170114356148 1.14918997765374 0.010327033781874828
5 1.14918997765374 1.1336874899901264 0.015502487663613618
6 1.1336874899901264 1.1104066754820405 0.023280814508085834
7 1.1104066754820405 1.075423756079303 0.03498291940273757
8 1.075423756079303 1.0228079787543636 0.05261577732493938
9 1.0228079787543636 0.943557415351523 0.07925056340284053
10 0.943557415351523 0.8239163074478012 0.11964110790372184
11 0.8239163074478012 0.6426317054986884 0.18128460194911278
12 0.6426317054986884 0.3662613327457731 0.2763703727529153
13 0.3662613327457731 0.05942144078132683 0.3068398919644463
14 0.05942144078132683 0.5265307297114032 0.4671092889300764
15 0.3312610956286144 0.0033985587354706803 0.3278625368

"\n@TODO: Maybe this doesn't work because I'm only relaxing tr((D-Dnew)F) but F depends on D as well\nit should be tr(Dnew F(Dnew)) = tr(D @ F(D))\n"

In [3]:
"""
Run SCF with low-rank density matrix

Parameters:
R: distance of H2s: H2 -----(R)----- H2
r: rank of rdm
"""

def prepare_system(R):
    mol = gto.Mole()
    mol.atom = f"""
    H 0 0 0
    H 0.74 0 0.
    H {R} 0 0
    H {R}.74 0 0
    # H {2*R} 0 0
    # H {2*R}.74 0 0
    """
    mol.basis = 'sto-3g'
    mol.unit = 'Angstrom'
    mol.build()

    # RHF calculation
    mf = scf.RHF(mol)
    mf.kernel()
    eri = torch.tensor(mol.intor('int2e'))
    print(f"Correct HF energy: {mf.e_tot}")
    return eri, mol, mf


def normalized_density(D, S, nocc):
    return nocc / 2 * D / torch.trace(D@S)


def purification_error(D, S, nocc):
    Dn = normalized_density(D, S, nocc)
    return torch.norm(Dn @ S @ Dn - Dn)


def hf_energy(U, d, hcore, eri, mol, rdm, S):
    D = buildD(U, d)
    # replace with low-rank version for D if available
    J = torch.einsum('rs,pqrs->pq', D, eri)
    K = torch.einsum('rs,prqs->pq', D, eri)
    enuc = mol.energy_nuc()
    F = 2*hcore + 0.5*(2 * J - K)
    return 0.5 * torch.trace(D@F) + enuc


def ev_purification(d, nocc, niter=10):
    d = d / torch.sum(d) * nocc / 2
    for _ in range(niter):
        d = 3 * d**2 - 2 * d**3
        d = d / torch.sum(d) * nocc / 2
    return d


def riemannian_steepest_descent(loss, S, r, nocc, hcore, h = 1e-4, iterations = 201, *args):
    # U = random_unitary(S.shape[0], r)
    # d = torch.abs(torch.randn(r, dtype=torch.float64))
    # d = ev_purification(d, nocc)

    """
    @TODO: try putting in correct guess and see if it stays there
    @TODO: How are d, U, and D different from method in cell above? 
            - Note: U seems coorect, so d must be wrong -> check this
    """

    d, U = torch.linalg.eigh(hcore)
    n = d.shape[0]
    d = d[n-r:]
    U = U[:, n-r:]
    d = ev_purification(d, nocc)
    print(U.shape, d.shape)
    print('U_start =\n', U)
    print('d_start = ', d)

    for i in range(iterations):
        Utmp = U.detach().clone().requires_grad_()
        dtmp = d.detach().clone().requires_grad_()
        L0 = loss(Utmp, dtmp, hcore, *args)
        L0.backward(retain_graph=True)
        dU = Utmp.grad.detach()
        dd = dtmp.grad.detach()

        U_bk = U.clone()
        U = U - h * dU
        d = d - h * dd

        U, _ = polar_decomp(U, r)
        d = ev_purification(d, nocc)
        d = d / torch.trace(buildD(U, d) @ S) * nocc
        # d = d / torch.trace(buildD(U, d) @ S) * nocc
        # d = d / torch.sum(d) * nocc

        L1 = loss(U, d, hcore, *args)

        err = torch.norm(L0 - L1)
        print(i, L0.item(), L1.item(), err.item(), d)

        if L1 < L0:
            h *= 1.5
        else:
            h /= 2.
            U = U_bk
            if h < 1e-12 or err < 1e-10:
                break
    return U, d


# Build two H3 molecules far apart (say 10 Angstroms separation)
R = 8
r = 1
eri, mol, mf = prepare_system(R)
hcore = torch.tensor(mf.get_hcore())
nocc = torch.sum(torch.tensor(mf.mo_occ))
S = torch.tensor(mf.get_ovlp())
D = torch.tensor(mf.make_rdm1())
Dn = normalized_density(D, S, nocc)

print('|D^2-D| = ', purification_error(D, S, nocc))

U, d = riemannian_steepest_descent(hf_energy, S, r, nocc, hcore, 1e-4, 150, eri, mol, D, S)
print('U_end =\n', U)
print('d_end = ', d)
print('E_end = ', hf_energy(U, d, hcore, eri, mol, D, S))
U = torch.tensor([[0.5, 0.5, 0.5, 0.5]], dtype=torch.float64).T
d = torch.tensor([2.2895], dtype=torch.float64)
print('E_manual = ', hf_energy(U, d, hcore, eri, mol, D, S))
print(S)

converged SCF energy = -2.23351786522334
Correct HF energy: -2.2335178652233445
|D^2-D| =  tensor(2.2778e-16, dtype=torch.float64)
torch.Size([4, 1]) torch.Size([1])
U_start =
 tensor([[ 0.5015],
        [-0.4985],
        [ 0.4985],
        [-0.5015]], dtype=torch.float64)
d_start =  tensor([2.], dtype=torch.float64)
0 1.3263428252137541 0.7916201025134746 0.5347227227002795 tensor([11.7599], dtype=torch.float64)
1 0.7916201025134746 0.7916199974810616 1.050324129892033e-07 tensor([11.7599], dtype=torch.float64)
2 0.7916199974810616 0.7916198387345534 1.5874650816094515e-07 tensor([11.7599], dtype=torch.float64)
3 0.7916198387345534 0.7916195979029437 2.408316097657348e-07 tensor([11.7599], dtype=torch.float64)
4 0.7916195979029437 0.7916192304975056 3.6740543807312065e-07 tensor([11.7599], dtype=torch.float64)
5 0.7916192304975056 0.7916186653416999 5.65155805709594e-07 tensor([11.7599], dtype=torch.float64)
6 0.7916186653416999 0.7916177853429156 8.799987842866841e-07 tensor([11.760

In [4]:
import torch
from pyscf import gto, scf

# Build and solve molecule
mol = gto.M(atom='H 0 0 0; H 0 0 1; H 0 0 2; H 0 0 3', basis='sto-3g')
mf = scf.RHF(mol).run()
nocc = torch.sum(torch.tensor(mf.mo_occ))
print(nocc)

# Get density matrix and overlap
D = torch.tensor(mf.make_rdm1())
S = torch.tensor(mf.get_ovlp())

def normalized_density(D, S, nocc):
    return nocc / 2 * D / torch.trace(D@S)

def purification_error(D, S, nocc):
    Dn = normalized_density(D, S, nocc)
    return torch.norm(Dn @ S @ Dn - Dn)

# Measure deviation from idempotency
error = purification_error(D, S, nocc)

print(f"||DSD - D|| = {error.item():.3e}")


converged SCF energy = -2.09854593699772
tensor(4., dtype=torch.float64)
||DSD - D|| = 4.152e-16
