In [1]:
"""
Test of manually building a low-rank density matrix that reproduces energy of (H_2)_2
"""

from pyscf import gto, scf
import numpy as np

# Build two H3 molecules far apart (say 10 Angstroms separation)
mol = gto.Mole()
mol.atom = '''
H 0 0 0
H 0.74 0 0.
H 9 0 0
H 9.74 0 0
'''
mol.basis = 'sto-3g'
mol.unit = 'Angstrom'
mol.build()

# RHF calculation
mf = scf.RHF(mol)
mf.kernel()
D = mf.make_rdm1()
h = mf.get_hcore()
eri = mol.intor('int2e')
J = np.einsum('rs,pqrs->pq', D, eri)
K = np.einsum('rs,prqs->pq', D, eri)

F = h + 0.5*(2 * J - K)
d, U = np.linalg.eigh(D)
E1 = 0.5 * np.trace(D@(h + F)) + mol.energy_nuc()
C = mf.mo_coeff

print(np.trace(D))
print(d)
print('|DF - FD|: ', np.trace(D@F - F@D))
print(mf.e_tot)

nocc = mf.mo_occ
print(C)
print(nocc)

i = 3
# D2 = U[:,i:i+1] @ np.diag(d[i:i+1]) @ U[:,i:i+1].T*2
davg = 0.5 * (d[2:3]+d[3:4])
D2 = U[:,i:i+1] @ np.diag(davg) @ U[:,i:i+1].T*2
D3 = (U[:,2:3]+U[:,3:4]) @ np.diag(davg) @ (U[:,2:3] + U[:,3:4]).T
print(U)
print('U[2:3]++ = ', (U[:,2:3]+U[:,3:4]).T)
print('d_avg = ', davg)
# D2 = U[:,2:4] @ np.diag(d[2:4]) @ U[:,2:4].T
# D2 = U[i:i+1, :].T @ np.diag(d[i:i+1]) @ U[i:i+1, :]*2
E2 = 0.5 * np.trace(D2@(h + F)) + mol.energy_nuc()
E3 = 0.5 * np.trace(D3@(h + F)) + mol.energy_nuc()
print('E1 = ', E1)
print('E2 = ', E2)
print('E3 = ', E3)
# 'Bosianise': Plug everything into lowest eigenvector
print("|E2 - E1| = ", np.linalg.norm(E2 - E1))
# Average between eigen-vectors & -values
print("|E3 - E1| = ", np.linalg.norm(E3 - E1))

# Confirm matching with PySCF Fock matrix
assert np.allclose(F, mf.get_fock()), "Mismatch in Fock matrix!"


converged SCF energy = -2.23351819973673
2.409822744204587
[-5.26303436e-17 -1.37505071e-17  1.20491137e+00  1.20491137e+00]
|DF - FD|:  -1.1102230246251565e-16
-2.2335181997367304
[[ 0.38808189  0.38808236  0.85733675 -0.85733641]
 [ 0.38809783  0.3880983  -0.85732954  0.8573292 ]
 [ 0.3880983  -0.38809783 -0.8573292  -0.85732954]
 [ 0.38808236 -0.38808189  0.85733641  0.85733675]]
[2. 2. 0. 0.]
[[ 0.70660877 -0.02691819 -0.49999164  0.49998782]
 [-0.70657974  0.02691708 -0.50001218  0.50000836]
 [ 0.02691709  0.70657974 -0.50000836 -0.50001218]
 [-0.02691819 -0.70660877 -0.49998782 -0.49999164]]
U[2:3]++ =  [[-3.82099164e-06 -3.82234611e-06 -1.00002054e+00 -9.99979461e-01]]
d_avg =  [1.20491137]
E1 =  -2.2335181997367304
E2 =  -2.233518198691973
E3 =  -2.23351819973674
|E2 - E1| =  1.0447571696658997e-09
|E3 - E1| =  9.769962616701378e-15


In [2]:
"""
Find low-rank representation of D by minimizing tr((D-D_lr)*F) (i.e. that reproduces energy)

Parameters:
R: distance of H2s: H2 -----(R)----- H2
r: rank of rdm
"""

from pyscf import gto, scf
import numpy as np
import torch
from scipy.linalg import polar


def prepare_H4(R):
    mol = gto.Mole()
    mol.atom = f"""
    H 0 0 0
    H 0.74 0 0.
    H {R} 0 0
    H {R}.74 0 0
    """
    mol.basis = 'sto-3g'
    mol.unit = 'Angstrom'
    mol.build()

    # RHF calculation
    mf = scf.RHF(mol)
    mf.kernel()
    D = torch.tensor(mf.make_rdm1(), dtype=torch.float64)
    h = mf.get_hcore()
    eri = mol.intor('int2e')
    J = np.einsum('rs,pqrs->pq', D, eri)
    K = np.einsum('rs,prqs->pq', D, eri)
    enuc = mol.energy_nuc()

    F = h + 0.5*(2 * J - K)
    # print(f"Correct HF energy: {mf.e_tot}")
    return torch.tensor(h + F, dtype=torch.float64), D, mf, enuc, mol

def energy(D, F, enuc):
    return 0.5 * torch.trace(D@F) + enuc

def random_unitary(m, r):
    A = torch.randn(m, r, dtype=torch.float64)
    Q, _ = torch.linalg.qr(A)
    return Q

def buildD(U, d):
    return U @ torch.diag(d) @ U.T

def loss(U, d, D, F):
    D2 = buildD(U, d)
    return torch.norm(torch.trace((D - D2) @ F))

def polar_decomp (m, r):   # express polar decomposition in terms of singular-value decomposition
    U, S, Vh = torch.linalg.svd(m, full_matrices=False)
    u = U @ Vh
    # p = Vh.T.conj() @ S.diag().to (dtype = m.dtype) @ Vh
    return  u, None

def output(i, L0, L1, U, d, r, D, F):
    Dnew = buildD(U, d)
    e = energy(Dnew, F, enuc).item()
    err = torch.trace(Dnew @ F - F @ Dnew)
    print(i, L0.item(), L1.item(), err.item(), e - mf.e_tot)

def riemannian_steepest_descent(D, F, loss, r, h = 1e-4, iterations = 201, *args):
    U = random_unitary(F.shape[0], r)
    d = torch.abs(torch.randn(r, dtype=torch.float64, requires_grad=True))
    d *= nocc / torch.sum(d)
    # d /= torch.sum(d)
    for i in range(iterations):
        # gradients
        Utmp = U.detach().clone().requires_grad_()
        dtmp = d.detach().clone().requires_grad_()
        L0 = loss(Utmp, dtmp, D, F, *args)
        L0.backward(retain_graph=True)
        dU = Utmp.grad.detach()
        dd = dtmp.grad.detach()

        # step
        U_bk = U.clone()
        U = U - h * dU
        d = d - h * dd
        # d = d / torch.sum(d) * nocc

        U, _ = polar_decomp(U, r)

        L1 = loss(U, d, D, F, *args)

        err = torch.norm(L1 - L0)
        print(i, L0.item(), L1.item(), err.item())
        # output(i, L0, L1, U, d, r, D, F)

        if L1 < L0:
            h *= 1.5
        else:
            h /= 2.
            U = U_bk
            if h < 1e-14 or err < 1e-12:
                break
    return U, d

# Build two H3 molecules far apart (say 10 Angstroms separation)
R = 8
r = 4
F, D, mf, enuc, mol = prepare_H4(R)
nocc = torch.sum(torch.tensor(mf.mo_occ))
U, d = riemannian_steepest_descent(D, F, loss, r, 1e-4, 200)
print(U, d)

Dnew = U @ torch.diag(d) @ U.T
print(Dnew)
print(energy(Dnew, F, enuc))
def hf_energy(U, d, hcore, eri, mol, rdm, S):
    D = buildD(U, d)
    # replace with low-rank version for D if available
    J = torch.einsum('rs,pqrs->pq', rdm, eri)
    K = torch.einsum('rs,prqs->pq', rdm, eri)
    enuc = mol.energy_nuc()
    F = 2*hcore + 0.5*(2 * J - K)
    return 0.5 * torch.trace(D@F) + enuc


hcore = torch.tensor(mf.get_hcore())
eri = torch.tensor(mol.intor('int2e'))
S = torch.tensor(mf.get_ovlp())
Dnew = buildD(U, d)
print('E_HF(U, d, Dnew) = ', hf_energy(U, d, hcore, eri, mol, Dnew, S))
print('energy(Dnew) = ', energy(Dnew, F, enuc))

print('E_HF(U, d, D) = ', hf_energy(U, d, hcore, eri, mol, D, S))
print('energy(D) = ', energy(D, F, enuc))
"""
@TODO: Maybe this doesn't work because I'm only relaxing tr((D-Dnew)F) but F depends on D as well
it should be tr(Dnew F(Dnew)) = tr(D @ F(D))
"""

converged SCF energy = -2.23351786522334
0 1.8953912965399151 1.8932569078239303 0.002134388715984814
1 1.8932569078239303 1.890055503335969 0.003201404487961357
2 1.890055503335969 1.8852537994178933 0.0048017039180756615
3 1.8852537994178933 1.8780521532262318 0.007201646191661526
4 1.8780521532262318 1.8672517420264043 0.010800411199827442
5 1.8672517420264043 1.8510557939171541 0.01619594810925018
6 1.8510557939171541 1.8267725038760114 0.024283290041142713
7 1.8267725038760114 1.7903719182541824 0.03640058562182902
8 1.7903719182541824 1.735827250248764 0.05454466800541846
9 1.735827250248764 1.6541414370877834 0.08168581316098056
10 1.6541414370877834 1.5319233254243005 0.12221811166348284
11 1.5319233254243005 1.3493445440027791 0.1825787814215214
12 1.3493445440027791 1.0773135113913543 0.2720310326114248
13 1.0773135113913543 0.6738431010985303 0.40347041029282404
14 0.6738431010985303 0.08003433719215103 0.5938087639063793
15 0.08003433719215103 0.7832330334059298 0.703198696

"\n@TODO: Maybe this doesn't work because I'm only relaxing tr((D-Dnew)F) but F depends on D as well\nit should be tr(Dnew F(Dnew)) = tr(D @ F(D))\n"

In [3]:
"""
Run SCF with low-rank density matrix

Parameters:
R: distance of H2s: H2 -----(R)----- H2
r: rank of rdm
"""

def prepare_system(R):
    mol = gto.Mole()
    mol.atom = f"""
    H 0 0 0
    H 0.74 0 0.
    H {R} 0 0
    H {R}.74 0 0
    # H {2*R} 0 0
    # H {2*R}.74 0 0
    """
    mol.basis = 'sto-3g'
    mol.unit = 'Angstrom'
    mol.build()

    # RHF calculation
    mf = scf.RHF(mol)
    mf.kernel()
    eri = torch.tensor(mol.intor('int2e'))
    print(f"Correct HF energy: {mf.e_tot}")
    return eri, mol, mf


def normalized_density(D, S, nocc):
    return nocc / 2 * D / torch.trace(D@S)


def purification_error(D, S, nocc):
    Dn = normalized_density(D, S, nocc)
    return torch.norm(Dn @ S @ Dn - Dn)


def hf_energy(U, d, hcore, eri, mol, rdm, S):
    D = buildD(U, d)
    # replace with low-rank version for D if available
    J = torch.einsum('rs,pqrs->pq', D, eri)
    K = torch.einsum('rs,prqs->pq', D, eri)
    enuc = mol.energy_nuc()
    F = 2*hcore + 0.5*(2 * J - K)
    return 0.5 * torch.trace(D@F) + enuc


def ev_purification(d, nocc, niter=10):
    d = d / torch.sum(d) * nocc / 2
    for _ in range(niter):
        d = 3 * d**2 - 2 * d**3
        d = d / torch.sum(d) * nocc / 2
    return d


def riemannian_steepest_descent(loss, S, r, nocc, hcore, h = 1e-4, iterations = 201, *args):
    # U = random_unitary(S.shape[0], r)
    # d = torch.abs(torch.randn(r, dtype=torch.float64))
    # d = ev_purification(d, nocc)

    """
    @TODO: try putting in correct guess and see if it stays there
    @TODO: How are d, U, and D different from method in cell above? 
            - Note: U seems coorect, so d must be wrong -> check this
    """

    d, U = torch.linalg.eigh(hcore)
    n = d.shape[0]
    d = d[n-r:]
    U = U[:, n-r:]
    d = ev_purification(d, nocc)
    print(U.shape, d.shape)
    print('U_start =\n', U)
    print('d_start = ', d)

    for i in range(iterations):
        Utmp = U.detach().clone().requires_grad_()
        dtmp = d.detach().clone().requires_grad_()
        L0 = loss(Utmp, dtmp, hcore, *args)
        L0.backward(retain_graph=True)
        dU = Utmp.grad.detach()
        dd = dtmp.grad.detach()

        U_bk = U.clone()
        U = U - h * dU
        d = d - h * dd

        U, _ = polar_decomp(U, r)
        d = ev_purification(d, nocc)
        d = d / torch.trace(buildD(U, d) @ S) * nocc
        # d = d / torch.trace(buildD(U, d) @ S) * nocc
        # d = d / torch.sum(d) * nocc

        L1 = loss(U, d, hcore, *args)

        err = torch.norm(L0 - L1)
        print(i, L0.item(), L1.item(), err.item(), d)

        if L1 < L0:
            h *= 1.5
        else:
            h /= 2.
            U = U_bk
            if h < 1e-12 or err < 1e-10:
                break
    return U, d


# Build two H3 molecules far apart (say 10 Angstroms separation)
R = 8
r = 1
eri, mol, mf = prepare_system(R)
hcore = torch.tensor(mf.get_hcore())
nocc = torch.sum(torch.tensor(mf.mo_occ))
S = torch.tensor(mf.get_ovlp())
D = torch.tensor(mf.make_rdm1())
Dn = normalized_density(D, S, nocc)

print('|D^2-D| = ', purification_error(D, S, nocc))

U, d = riemannian_steepest_descent(hf_energy, S, r, nocc, hcore, 1e-4, 150, eri, mol, D, S)
print('U_end =\n', U)
print('d_end = ', d)
print('E_end = ', hf_energy(U, d, hcore, eri, mol, D, S))
U = torch.tensor([[0.5, 0.5, 0.5, 0.5]], dtype=torch.float64).T
d = torch.tensor([2.2895], dtype=torch.float64)
print('E_manual = ', hf_energy(U, d, hcore, eri, mol, D, S))
print(S)

converged SCF energy = -2.23351786522334
Correct HF energy: -2.2335178652233445
|D^2-D| =  tensor(3.0532e-16, dtype=torch.float64)
torch.Size([4, 1]) torch.Size([1])
U_start =
 tensor([[ 0.5015],
        [-0.4985],
        [ 0.4985],
        [-0.5015]], dtype=torch.float64)
d_start =  tensor([2.], dtype=torch.float64)
0 1.3263428252137541 0.7916201025134746 0.5347227227002795 tensor([11.7599], dtype=torch.float64)
1 0.7916201025134746 0.7916199974810616 1.050324129892033e-07 tensor([11.7599], dtype=torch.float64)
2 0.7916199974810616 0.7916198387345534 1.5874650816094515e-07 tensor([11.7599], dtype=torch.float64)
3 0.7916198387345534 0.7916195979029437 2.408316097657348e-07 tensor([11.7599], dtype=torch.float64)
4 0.7916195979029437 0.7916192304975056 3.6740543807312065e-07 tensor([11.7599], dtype=torch.float64)
5 0.7916192304975056 0.7916186653416999 5.65155805709594e-07 tensor([11.7599], dtype=torch.float64)
6 0.7916186653416999 0.7916177853429156 8.799987842866841e-07 tensor([11.760

In [4]:
import torch
from pyscf import gto, scf

# Build and solve molecule
mol = gto.M(atom='H 0 0 0; H 0 0 1; H 0 0 2; H 0 0 3', basis='sto-3g')
mf = scf.RHF(mol).run()
nocc = torch.sum(torch.tensor(mf.mo_occ))
print(nocc)

# Get density matrix and overlap
D = torch.tensor(mf.make_rdm1())
S = torch.tensor(mf.get_ovlp())

def normalized_density(D, S, nocc):
    return nocc / 2 * D / torch.trace(D@S)

def purification_error(D, S, nocc):
    Dn = normalized_density(D, S, nocc)
    return torch.norm(Dn @ S @ Dn - Dn)

# Measure deviation from idempotency
error = purification_error(D, S, nocc)

print(f"||DSD - D|| = {error.item():.3e}")


converged SCF energy = -2.09854593699772
tensor(4., dtype=torch.float64)
||DSD - D|| = 1.515e-16
